experimental_monorepo_root=true

[tools]
bun = "1.3.14"
go = "1.24"
node = "26"

[env]
MISE_EXPERIMENTAL=true

[monorepo]
config_roots = [
    "_apps/*",
]

[tasks.mod-download]
run = "go mod download"

[tasks.install]
run = "bun i && go mod download"

[tasks.test-integration]
depends = ["install"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  mise //_apps/_worker:build --tiny
else
  mise //_apps/_worker:build
fi
bun run vitest run
"""

[tasks.test-lib]
depends = ["mod-download"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  GOOS=js GOARCH=wasm tinygo test -timeout 500ms -bench=. ./...
else
  go test -timeout 1000ms ./...
  GOOS=js GOARCH=wasm go test -exec=$(go env GOROOT)/lib/wasm/go_js_wasm_exec -timeout 500ms ./...
fi
"""

[tasks.bench]
depends = ["install"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  GOOS=js GOARCH=wasm tinygo test -timeout 500ms -bench=. ./... | grep -v '\\[no test files\\]'
else
  GOOS=js GOARCH=wasm go test -exec=$(go env GOROOT)/lib/wasm/go_js_wasm_exec -timeout 500ms -bench=. ./... | grep -v '\\[no test files\\]'
fi
"""

[tasks.lint]
run = "golangci-lint run"
