experimental_monorepo_root=true

[tools]
bun = "1.3.14"
go = "1.24"

[env]
MISE_EXPERIMENTAL=1
GOOS="js"
GOARCH="wasm"

[monorepo]
config_roots = [
    "_apps/*",
]

[tasks.install]
run = "bun i && go mod download"

[tasks.test-integration]
depends = ["install"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  mise //_apps/_worker:build --tiny
else
  mise //_apps/_worker:build
fi
bun run vitest
"""

[tasks.test-lib]
depends = ["install"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  GOOS=js GOARCH=wasm tinygo test -timeout 500ms -bench=. ./...
else
  GOOS=js GOARCH=wasm go test -exec=$(go env GOROOT)/lib/wasm/go_js_wasm_exec -timeout 500ms ./...
fi
"""

[tasks.bench]
depends = ["install"]
run = """
#!/usr/bin/env bash
if [ "$1" = "--tiny" ]; then
  GOOS=js GOARCH=wasm tinygo test -timeout 500ms -bench=. ./...
else
  GOOS=js GOARCH=wasm go test -exec=$(go env GOROOT)/lib/wasm/go_js_wasm_exec -timeout 500ms ./...
fi
"""

[tasks.lint]
run = "GOOS=js GOARCH=wasm golangci-lint run"
