packages:
  - _apps/_worker
  - _apps/_ultimate-express
  - _apps/_hono
  - _apps/_bun
  - _apps/_deno

color: always
sharedWorkspaceLockfile: false
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

overrides:
  devalue@<5.3.2: '>=5.3.2'
