//go:build durableobject
/*
DO NOT EDIT THIS FILE - Auto generated by workers-go cli
########   #######     ##    ##  #######  ########    ######## ########  #### ########
##     ## ##     ##    ###   ## ##     ##    ##       ##       ##     ##  ##     ##
##     ## ##     ##    ####  ## ##     ##    ##       ##       ##     ##  ##     ##
##     ## ##     ##    ## ## ## ##     ##    ##       ######   ##     ##  ##     ##
##     ## ##     ##    ##  #### ##     ##    ##       ##       ##     ##  ##     ##
##     ## ##     ##    ##   ### ##     ##    ##       ##       ##     ##  ##     ##
########   #######     ##    ##  #######     ##       ######## ########  ####    ##
DO NOT EDIT THIS FILE - Auto generated by workers-go cli
*/
package main

import (
	"context"
	"encoding/json"
)
// Autogenerated
func (d *MyDurableObject) _WhatTimsIsIt(c context.Context, data [][]byte) [][]byte {
  var a0 Greeting
  json.Unmarshal(data[0], &a0)
  
  r0 :=d.WhatTimsIsIt(c,&a0)
  b0, _ := json.Marshal(r0)
  return [][]byte{b0 }
}
// Autogenerated
func (d *MyDurableObject) _Goodbye(c context.Context, data [][]byte) [][]byte {
  var a0 Greeting
  json.Unmarshal(data[0], &a0)
  
  var a1 int64
  json.Unmarshal(data[1], &a1)
  
  r0,r1 :=d.Goodbye(c,&a0,&a1)
  b0, _ := json.Marshal(r0)
  b1, _ := json.Marshal(r1)
  return [][]byte{b0,b1 }
}
// Autogenerated
func (d *MyDurableObject) _SayHello(c context.Context, data [][]byte) [][]byte {
  var a0 Greeting
  json.Unmarshal(data[0], &a0)
  
  r0 :=d.SayHello(c,&a0)
  b0, _ := json.Marshal(r0)
  return [][]byte{b0 }
}
// Autogenerated
func (d *MyDurableObject) _init(c context.Context, data [][]byte) [][]byte {
  d.init(c)
  return [][]byte{ }
}
// Autogenerated
func main() {
  var _MyDurableObject = MyDurableObject{}
  _MyDurableObject.New("MyDurableObject")
  _MyDurableObject.AddRPC("_WhatTimsIsIt", _MyDurableObject._WhatTimsIsIt)
  _MyDurableObject.AddRPC("_Goodbye", _MyDurableObject._Goodbye)
  _MyDurableObject.AddRPC("_SayHello", _MyDurableObject._SayHello)
  _MyDurableObject.AddFetch(_MyDurableObject.fetch)
  _MyDurableObject.AddRPC("_init", _MyDurableObject._init)
	select {}
}
