name = "workers-go"
main = "bin/main.ts"
compatibility_date = "2025-08-12"

[build]
command = "go install codeberg.org/darckfast/workers-go/cmd/workers-go && workers-go -i ./pkg -o ./bin"

[[queues.consumers]]
queue = "TEST-QUEUE"
max_batch_size = 10
max_batch_timeout = 5
