name = "workers-go"
main = "main.ts"
compatibility_date = "2025-08-12"

[build]
command = "mise run build"
watch_dir = [ "pkg" ]

[[queues.consumers]]
queue = "TEST-QUEUE"
max_batch_size = 10
max_batch_timeout = 5
