// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package durableobjects

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareDurableobjectsProposal(in *jlexer.Lexer, out *SqlStorageCursorProp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "done":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Done = bool(in.Bool())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Value = make(map[string]interface{})
				} else {
					out.Value = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.Value)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareDurableobjectsProposal(out *jwriter.Writer, in SqlStorageCursorProp) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Done {
		const prefix string = ",\"done\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.Done))
	}
	if len(in.Value) != 0 {
		const prefix string = ",\"value\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Value {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if m, ok := v2Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v2Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v2Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SqlStorageCursorProp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareDurableobjectsProposal(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SqlStorageCursorProp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareDurableobjectsProposal(l, v)
}
