name = "workers-go"
main = "bin/main.ts"
compatibility_date = "2025-08-12"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "go install codeberg.org/darckfast/workers-go/cmd/workers-go && workers-go -i ."
