// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package queues

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues(in *jlexer.Lexer, out *QueueSendResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metadata).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues(out *jwriter.Writer, in QueueSendResult) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"metadata\":"
		first = false
		out.RawString(prefix[1:])
		(in.Metadata).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QueueSendResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QueueSendResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues(l, v)
}
func easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues1(in *jlexer.Lexer, out *QueueMetrics) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "backlogCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BacklogCount = int64(in.Int64())
			}
		case "backlogBytes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BacklogBytes = int64(in.Int64())
			}
		case "oldestMessageTimestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OldestMessageTimestamp = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues1(out *jwriter.Writer, in QueueMetrics) {
	out.RawByte('{')
	first := true
	_ = first
	if in.BacklogCount != 0 {
		const prefix string = ",\"backlogCount\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.BacklogCount))
	}
	if in.BacklogBytes != 0 {
		const prefix string = ",\"backlogBytes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.BacklogBytes))
	}
	if in.OldestMessageTimestamp != 0 {
		const prefix string = ",\"oldestMessageTimestamp\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.OldestMessageTimestamp))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v QueueMetrics) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *QueueMetrics) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues1(l, v)
}
func easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues2(in *jlexer.Lexer, out *Metadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "metrics":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metrics).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues2(out *jwriter.Writer, in Metadata) {
	out.RawByte('{')
	first := true
	_ = first
	if true {
		const prefix string = ",\"metrics\":"
		first = false
		out.RawString(prefix[1:])
		(in.Metrics).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Metadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Metadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeCodebergOrgDarckfastWorkersGoPlatformCloudflareQueues2(l, v)
}
