name = "workers-go"
main = "./main.ts"
compatibility_date = "2025-08-12"

[vars]
API_HOST = "example.com"
API_ACCOUNT_ID = "example_user"
SERVICE_X_DATA = { URL = "service-x-api.dev.example", MY_ID = 123 }

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "TEST_NAMESPACE"
id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = 'TEST_BUCKET'
bucket_name = '0123'

[[d1_databases]]
binding = "DB"
database_name = "prd"
database_id = "00000000-0000-0000-0000-000000000000"

[[queues.producers]]
queue = "TEST-QUEUE"
binding = "TEST_QUEUE"

[[queues.consumers]]
queue = "TEST-QUEUE"
max_batch_size = 10
max_batch_timeout = 5

# Cloudflare Container
# [[containers]]
# name = "go-container"
# class_name = "GoContainer"
# image = "./Dockerfile"
# max_instances = 3

# Cloudflare Container
[[durable_objects.bindings]]
class_name = "GoContainer"
name = "GO_CONTAINER"

# Normal Durable object
[[durable_objects.bindings]]
class_name = "TestDurableObject"
name = "TEST_DO"

# The class GoContainer is used by Cloudflare Container
[[migrations]]
new_sqlite_classes = ["GoContainer", "TestDurableObject"]
tag = "v1"
