[tools]
go = "1.24"
node = "24"

[tasks.install]
run = "npm i && go mod download"

[tasks.build]
depends = ["install"]
run = """
  cp $(go env GOROOT)/lib/wasm/wasm_exec.js ./bin/wasm_exec.js
  GOOS=js GOARCH=wasm go build -o ./bin/app.wasm ./main.go
"""

[tasks.dev]
depends = ["build"]
run = "npx tsx watch index.ts"

[tasks.test]
depends = ["build"]
run = "node --test index.spec.ts"
