name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "platform/**"
      - "cmd/**"
      - "internal/**"

permissions:
  contents: read

jobs:
  lint:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "/root/.local/bin" >> $GITHUB_PATH
      - run: mise lint
