name: PR Tests
on: [pull_request]

env:
  GOOS: js
  GOARCH: wasm

jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.21 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: echo "$(go env GOROOT)/lib/wasm" >> $GITHUB_PATH
      - run: pnpm i

      - name: Test Go
        shell: bash
        run: pnpm run test:go

      - name: Test Worker
        shell: bash
        run: pnpm run test:run
