name: PR Tests
on: [pull_request]

env:
  GOOS: js
  GOARCH: wasm
  MISE_EXPERIMENTAL: true

jobs:
  test-bun:
    name: Test Bun
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //_apps//_bun:test

  test-deno:
    name: Test Deno
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //_apps//_deno:test

  test-hono:
    name: Test Hono
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //_apps//_hono:test
  test-uws:
    name: Test uWS
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //_apps//_uws:test

  test-worker:
    name: Test Worker Integration
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //:test-integration

  test-go:
    name: Test Go Lib
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: echo "/root/.local/bin" >> $GITHUB_PATH
      - run: /root/.local/bin/mise //:test-lib
