name: PR
on: [pull_request]

jobs:
  ci:
    strategy:
      matrix:
        go-version: [ 1.24 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Test Go
        shell: bash
        run: PATH='$PATH:$(go env GOROOT)/lib/wasm' pnpm run test:go

      - name: Test Worker
        shell: bash
        run: pnpm run test:ci
