name: PR Tests
on: [pull_request]

env:
  GOOS: js
  GOARCH: wasm

jobs:
  test-bun:
    name: Test Bun
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: /root/.local/bin/mise bun test

  test-deno:
    name: Test Deno
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: /root/.local/bin/mise deno test

  # test-hono:
  #   name: Test Hono
  #   runs-on: codeberg-small-lazy
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Install mise
  #       run: |
  #         curl https://mise.run | sh
  #     - run: /root/.local/bin/mise hono test
  #
  # test-uws:
  #   name: Test uWS
  #   runs-on: codeberg-small-lazy
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Install mise
  #       run: |
  #         curl https://mise.run | sh
  #     - run: /root/.local/bin/mise uws test

  test-worker:
    name: Test Worker
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: /root/.local/bin/mise test

  test-go:
    name: Test Go
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v6
      - name: Install mise
        run: |
          curl https://mise.run | sh
      - run: /root/.local/bin/mise test:go

