name: staticcheck
on: [pull_request]

env:
  GOOS: js
  GOARCH: wasm

jobs:
  ci:
    strategy:
      matrix:
        go-version: [ 1.24 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - run: go vet ./...

    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
